spring.application.name=Taxi-Booking-Project


# ===============================
# MySQL Database Configuration
# ===============================
#spring.datasource.url=jdbc:mysql://localhost:3306/taxibooking
#spring.datasource.username=root
#spring.datasource.password=Sai@12345
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.datasource.url=jdbc:mysql://taxibooking.c0vou648we7d.us-east-1.rds.amazonaws.com:3306/taxibooking
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
#spring.datasource.username=root
#spring.datasource.password=kfHvCrVVQfdWiWVabhaAkZTrZJwWNGkU
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Thymeleaf Configuration
# ===============================
spring.thymeleaf.cache=false

# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=077.sonusingh@gmail.com
spring.mail.password=fgespsmhsetnmqya

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
